spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gymapp}
    username: ${SPRING_DATASOURCE_USERNAME:gymapp}
    password: ${SPRING_DATASOURCE_PASSWORD:gymapp}
  flyway:
    enabled: true

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
